name: Deploy
on:
  workflow_run:
    workflows: ['Build project', 'Check code', 'Lint code', 'Test e2e', 'Test unit']
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm environment
        uses: ./.github/actions/setup-pnpm-environment
      - name: Build project with Vite
        uses: ./.github/actions/build-project
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
